# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.srcs/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0.xci
# IP: The module: 'system_axi_gpio_11_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_11_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_11_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_11_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.srcs/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0.xci
# IP: The module: 'system_axi_gpio_11_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_11_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_11_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_11_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
