# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.srcs/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2.xci
# IP: The module: 'system_axi_gpio_8_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.gen/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_8_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.gen/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_8_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.gen/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_8_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.srcs/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2.xci
# IP: The module: 'system_axi_gpio_8_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.gen/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_8_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.gen/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_8_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/CPU_PID/tmp/Complete_PID/Complete_PID.gen/sources_1/bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_8_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
