# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_EXTERNAL_FINAL/PID_EXTERNAL_FINAL.srcs/sources_1/bd/system/ip/system_xbar_7/system_xbar_7.xci
# IP: The module: 'system_xbar_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_EXTERNAL_FINAL/PID_EXTERNAL_FINAL.gen/sources_1/bd/system/ip/system_xbar_7/system_xbar_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_EXTERNAL_FINAL/PID_EXTERNAL_FINAL.srcs/sources_1/bd/system/ip/system_xbar_7/system_xbar_7.xci
# IP: The module: 'system_xbar_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_EXTERNAL_FINAL/PID_EXTERNAL_FINAL.gen/sources_1/bd/system/ip/system_xbar_7/system_xbar_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
