# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/clocks.xdc

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_low_pass_0_0/system_low_pass_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_low_pass_0_0 || ORIG_REF_NAME==system_low_pass_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Scan_0_0/system_Scan_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Scan_0_0 || ORIG_REF_NAME==system_Scan_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Voltage_Holder_0_0/system_Voltage_Holder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Voltage_Holder_0_0 || ORIG_REF_NAME==system_Voltage_Holder_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_0/system_signal_split_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_0_0 || ORIG_REF_NAME==system_signal_split_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Voltage_Holder_1_0/system_Voltage_Holder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Voltage_Holder_1_0 || ORIG_REF_NAME==system_Voltage_Holder_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_1_0/system_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_1_0 || ORIG_REF_NAME==system_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_divider_0_0/system_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_divider_0_0 || ORIG_REF_NAME==system_divider_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_1_0/system_signal_split_2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_1_0 || ORIG_REF_NAME==system_signal_split_2_1_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_1_1/system_signal_split_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_1_1 || ORIG_REF_NAME==system_signal_split_1_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_1_1/system_signal_split_2_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_1_1 || ORIG_REF_NAME==system_signal_split_2_1_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_2_1/system_signal_split_2_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_2_1 || ORIG_REF_NAME==system_signal_split_2_2_1} -quiet] -quiet

# IP: bd/system/ip/system_Data_b_Pack_0_0/system_Data_b_Pack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Data_b_Pack_0_0 || ORIG_REF_NAME==system_Data_b_Pack_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Add_0_0/system_Add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Add_0_0 || ORIG_REF_NAME==system_Add_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_1_2/system_signal_split_2_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_1_2 || ORIG_REF_NAME==system_signal_split_2_1_2} -quiet] -quiet

# IP: bd/system/ip/system_PID_Inputs_Pack_0_0/system_PID_Inputs_Pack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PID_Inputs_Pack_0_0 || ORIG_REF_NAME==system_PID_Inputs_Pack_0_0} -quiet] -quiet

# IP: bd/system/ip/system_LED_Contoller_0_0/system_LED_Contoller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_LED_Contoller_0_0 || ORIG_REF_NAME==system_LED_Contoller_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Selector_0_0/system_Selector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Selector_0_0 || ORIG_REF_NAME==system_Selector_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Ramp_0_0/system_Ramp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Ramp_0_0 || ORIG_REF_NAME==system_Ramp_0_0} -quiet] -quiet

# IP: bd/system/ip/system_PI_ctrl_0_0/system_PI_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PI_ctrl_0_0 || ORIG_REF_NAME==system_PI_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_scale_0_0/system_scale_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_scale_0_0 || ORIG_REF_NAME==system_scale_0_0} -quiet] -quiet

# IP: bd/system/ip/system_B_Select_0_0/system_B_Select_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_B_Select_0_0 || ORIG_REF_NAME==system_B_Select_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Add_0_1/system_Add_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Add_0_1 || ORIG_REF_NAME==system_Add_0_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_4_0/system_signal_split_2_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_4_0 || ORIG_REF_NAME==system_signal_split_2_4_0} -quiet] -quiet

# IP: bd/system/ip/system_External_Digital_Inp_0_0/system_External_Digital_Inp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_External_Digital_Inp_0_0 || ORIG_REF_NAME==system_External_Digital_Inp_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_18/system_axi_gpio_0_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_18 || ORIG_REF_NAME==system_axi_gpio_0_18} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_19/system_axi_gpio_0_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_19 || ORIG_REF_NAME==system_axi_gpio_0_19} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_1 || ORIG_REF_NAME==system_axi_gpio_1_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_0/system_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_0 || ORIG_REF_NAME==system_axi_gpio_4_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_1/system_axi_gpio_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_1 || ORIG_REF_NAME==system_axi_gpio_4_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_2/system_axi_gpio_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_2 || ORIG_REF_NAME==system_axi_gpio_4_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_3/system_axi_gpio_4_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_3 || ORIG_REF_NAME==system_axi_gpio_4_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_4/system_axi_gpio_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_4 || ORIG_REF_NAME==system_axi_gpio_4_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_5/system_axi_gpio_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_5 || ORIG_REF_NAME==system_axi_gpio_4_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_6/system_axi_gpio_10_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_6 || ORIG_REF_NAME==system_axi_gpio_10_6} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_7/system_axi_gpio_10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_7 || ORIG_REF_NAME==system_axi_gpio_10_7} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_8/system_axi_gpio_10_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_8 || ORIG_REF_NAME==system_axi_gpio_10_8} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_9/system_axi_gpio_10_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_9 || ORIG_REF_NAME==system_axi_gpio_10_9} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_10/system_axi_gpio_10_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_10 || ORIG_REF_NAME==system_axi_gpio_10_10} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_11/system_axi_gpio_10_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_11 || ORIG_REF_NAME==system_axi_gpio_10_11} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_12/system_axi_gpio_10_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_12 || ORIG_REF_NAME==system_axi_gpio_10_12} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_16_1/system_axi_gpio_16_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_16_1 || ORIG_REF_NAME==system_axi_gpio_16_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_16_2/system_axi_gpio_16_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_16_2 || ORIG_REF_NAME==system_axi_gpio_16_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_17_3/system_axi_gpio_17_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_17_3 || ORIG_REF_NAME==system_axi_gpio_17_3} -quiet] -quiet

# IP: bd/system/ip/system_xbar_7/system_xbar_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_7 || ORIG_REF_NAME==system_xbar_7} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_7/system_ps7_0_axi_periph_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_7 || ORIG_REF_NAME==system_ps7_0_axi_periph_7} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_20_0/system_axi_gpio_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_20_0 || ORIG_REF_NAME==system_axi_gpio_20_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_20_1/system_axi_gpio_20_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_20_1 || ORIG_REF_NAME==system_axi_gpio_20_1} -quiet] -quiet

# IP: bd/system/ip/system_Square_Wave_0_0/system_Square_Wave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Square_Wave_0_0 || ORIG_REF_NAME==system_Square_Wave_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_22_0/system_axi_gpio_22_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_22_0 || ORIG_REF_NAME==system_axi_gpio_22_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_EXTERNAL_FINAL/PID_EXTERNAL_FINAL.gen/sources_1/bd/system/system_ooc.xdc
