# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/clocks.xdc

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_low_pass_0_0/system_low_pass_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_low_pass_0_0 || ORIG_REF_NAME==system_low_pass_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Scan_0_0/system_Scan_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Scan_0_0 || ORIG_REF_NAME==system_Scan_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Voltage_Holder_0_0/system_Voltage_Holder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Voltage_Holder_0_0 || ORIG_REF_NAME==system_Voltage_Holder_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_0/system_signal_split_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_0_0 || ORIG_REF_NAME==system_signal_split_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Voltage_Holder_1_0/system_Voltage_Holder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Voltage_Holder_1_0 || ORIG_REF_NAME==system_Voltage_Holder_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_1_0/system_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_1_0 || ORIG_REF_NAME==system_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_divider_0_0/system_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_divider_0_0 || ORIG_REF_NAME==system_divider_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_1_0/system_signal_split_2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_1_0 || ORIG_REF_NAME==system_signal_split_2_1_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_1_1/system_signal_split_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_1_1 || ORIG_REF_NAME==system_signal_split_1_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_1_1/system_signal_split_2_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_1_1 || ORIG_REF_NAME==system_signal_split_2_1_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_2_1/system_signal_split_2_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_2_1 || ORIG_REF_NAME==system_signal_split_2_2_1} -quiet] -quiet

# IP: bd/system/ip/system_Data_b_Pack_0_0/system_Data_b_Pack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Data_b_Pack_0_0 || ORIG_REF_NAME==system_Data_b_Pack_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Add_0_0/system_Add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Add_0_0 || ORIG_REF_NAME==system_Add_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_1_2/system_signal_split_2_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_1_2 || ORIG_REF_NAME==system_signal_split_2_1_2} -quiet] -quiet

# IP: bd/system/ip/system_PID_Inputs_Pack_0_0/system_PID_Inputs_Pack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PID_Inputs_Pack_0_0 || ORIG_REF_NAME==system_PID_Inputs_Pack_0_0} -quiet] -quiet

# IP: bd/system/ip/system_LED_Contoller_0_0/system_LED_Contoller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_LED_Contoller_0_0 || ORIG_REF_NAME==system_LED_Contoller_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Selector_0_0/system_Selector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Selector_0_0 || ORIG_REF_NAME==system_Selector_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Ramp_0_0/system_Ramp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Ramp_0_0 || ORIG_REF_NAME==system_Ramp_0_0} -quiet] -quiet

# IP: bd/system/ip/system_PI_ctrl_0_0/system_PI_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PI_ctrl_0_0 || ORIG_REF_NAME==system_PI_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_scale_0_0/system_scale_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_scale_0_0 || ORIG_REF_NAME==system_scale_0_0} -quiet] -quiet

# IP: bd/system/ip/system_B_Select_0_0/system_B_Select_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_B_Select_0_0 || ORIG_REF_NAME==system_B_Select_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Add_0_1/system_Add_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Add_0_1 || ORIG_REF_NAME==system_Add_0_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_4_0/system_signal_split_2_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_4_0 || ORIG_REF_NAME==system_signal_split_2_4_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_17/system_axi_gpio_0_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_17 || ORIG_REF_NAME==system_axi_gpio_0_17} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_2/system_axi_gpio_10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_2 || ORIG_REF_NAME==system_axi_gpio_10_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_6_1/system_axi_gpio_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_6_1 || ORIG_REF_NAME==system_axi_gpio_6_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_3/system_axi_gpio_10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_3 || ORIG_REF_NAME==system_axi_gpio_10_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_4/system_axi_gpio_10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_4 || ORIG_REF_NAME==system_axi_gpio_10_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_5_1/system_axi_gpio_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_5_1 || ORIG_REF_NAME==system_axi_gpio_5_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_5/system_axi_gpio_10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_5 || ORIG_REF_NAME==system_axi_gpio_10_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_8_2/system_axi_gpio_8_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_8_2 || ORIG_REF_NAME==system_axi_gpio_8_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_16_0/system_axi_gpio_16_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_16_0 || ORIG_REF_NAME==system_axi_gpio_16_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_17_1/system_axi_gpio_17_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_17_1 || ORIG_REF_NAME==system_axi_gpio_17_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_17_2/system_axi_gpio_17_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_17_2 || ORIG_REF_NAME==system_axi_gpio_17_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_11/system_axi_gpio_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_11 || ORIG_REF_NAME==system_axi_gpio_0_11} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_18_1/system_axi_gpio_18_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_18_1 || ORIG_REF_NAME==system_axi_gpio_18_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_12/system_axi_gpio_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_12 || ORIG_REF_NAME==system_axi_gpio_0_12} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_13/system_axi_gpio_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_13 || ORIG_REF_NAME==system_axi_gpio_0_13} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_18_2/system_axi_gpio_18_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_18_2 || ORIG_REF_NAME==system_axi_gpio_18_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_21_0/system_axi_gpio_21_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_21_0 || ORIG_REF_NAME==system_axi_gpio_21_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_14/system_axi_gpio_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_14 || ORIG_REF_NAME==system_axi_gpio_0_14} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_8_3/system_axi_gpio_8_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_8_3 || ORIG_REF_NAME==system_axi_gpio_8_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_22_0/system_axi_gpio_22_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_22_0 || ORIG_REF_NAME==system_axi_gpio_22_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_15/system_axi_gpio_0_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_15 || ORIG_REF_NAME==system_axi_gpio_0_15} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_16/system_axi_gpio_0_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_16 || ORIG_REF_NAME==system_axi_gpio_0_16} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_11_0 || ORIG_REF_NAME==system_axi_gpio_11_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_23_0/system_axi_gpio_23_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_23_0 || ORIG_REF_NAME==system_axi_gpio_23_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_6/system_xbar_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_6 || ORIG_REF_NAME==system_xbar_6} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_6/system_ps7_0_axi_periph_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_6 || ORIG_REF_NAME==system_ps7_0_axi_periph_6} -quiet] -quiet

# IP: bd/system/ip/system_Square_Wave_0_0/system_Square_Wave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Square_Wave_0_0 || ORIG_REF_NAME==system_Square_Wave_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_24_0/system_axi_gpio_24_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_24_0 || ORIG_REF_NAME==system_axi_gpio_24_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_3_0/system_tier2_xbar_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_3_0 || ORIG_REF_NAME==system_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_CPU_FINAL/PID_CPU_FINAL.gen/sources_1/bd/system/system_ooc.xdc
